[package]
name = "yoraba-taiju"
version = "0.1.0"
authors = ["kaede"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
heapless = "0.6.1"
typenum = "1.13.0"
anyhow = "1.0.40"
